### ISSUE TITLE
Beta distribution alpha=1 beta=1 always equals NaN for samples

### ISSUE THREAD

**Issue by rustyconover** [AlexeySKiselev/randomjs#10]
This doesn't seem like the correct result.

**Comment by AlexeySKiselev** [comment]
Dear Rusty, thanks for Your attention. This bug fixed [here](https://github.com/AlexeySKiselev/randomjs/pull/11). Thanks for using unirand.

**Comment by AlexeySKiselev** [comment]
Necessary tests added.
